services:
  - type: web
    name: whatsapp-auto-sender
    env: node
    repo: https://github.com/Tabbu-Arain/Wp-Auto-Server
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
